sudo: required
services:
    - docker

before_install:
    - docker build -t avichauhan6832/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true avichauhan6832/docker-react npm run test